var currentdate=new Date()
console.log(currentdate);
var time=currentdate.getFullYear()
console.log(time)
var day=currentdate.getDay()
console.log(day)
var month=currentdate.getMonth()
console.log(month)
var hours=currentdate.getHours()
console.log(hours)
var seconds=currentdate.getSeconds()
console.log(seconds)
var date=currentdate.toDateString()
console.log(date)
var local=currentdate.toLocaleString()
console.log(local)
var millisec=currentdate.getMilliseconds()
console.log(millisec)

